version: "2"
services:
  postgresql-db:
    container_name: postgresql.db-local
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5433:5432 # postgresql-port:local-port
    env_file:
      - ./docker.env

