version: '3'

services:

  mongo:
    container_name: mongo-dev
    image: mongo
    restart: always
    networks:
      - mongo-compose-network
    ports:
      - 28017:27017
    env_file:
      - ./docker.env
    # docker.envにまとめる
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./configdb:/data/configdb
      - mongoDataStore:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - mongo-compose-network
    env_file:
      - ./docker.env
    # docker.envにまとめる
    #environment:
    #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
    #  ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

networks:
  mongo-compose-network:
    driver: bridge
volumes:
  mongoDataStore:
    driver: local

