version: "2"
services:
  sqlserver-db:
    container_name: sqlserver.db-local
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 1433:1433
    env_file:
      - ./docker.env

